### ISSUE TITLE
Incompatible types between gitbase-spark-connector and gitbase

### ISSUE THREAD

**Issue by erizocosmico** [src-d/gitbase-spark-connector#32]
In gitbase, UastExtract (for example) is of type `sql.Array(sql.Text)`, which translates to `JSON` on the wire. To Spark, a `BinaryType` arrives, but `UastExtract` expects `Seq[String]`, so once the UDF is pushed down to gitbase, there's an incompatibility between types.

**Comment by ajnavarro** [comment]
I was thinking of how to make this work. 

At first, I thought of having a rule checking if the output is a JSON from `uast_extract` and if yes, convert it to `Seq[String]`. This rule can just check the topmost Projection on the tree, changing only the type if the UDF is there. But this can have a lot of corner cases.

My second idea and the easiest to implement is to change `UastExtract` to return a BinaryType as a JSON, and then create a new UDF called `UastExtractParse` to generate a `Seq[String]` getting the output of `UastExtract`. Doing this, we can generate a DF from a SQL query that will be pushed down, and then apply `UastExtractParse` to the column with results from `uast_extract` from gitbase.

Having (2) we can implement later (1), because the functionality is the same.

@mcarmonaa @erizocosmico WDYT?

**Comment by erizocosmico** [comment]
LGTM @ajnavarro

**Comment by mcarmonaa** [comment]
sounds good
